# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import voice_analysis_pb2 as voice__analysis__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in voice_analysis_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VoiceIntegrityServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeStream = channel.stream_stream(
                '/voiceintegrity.VoiceIntegrityService/AnalyzeStream',
                request_serializer=voice__analysis__pb2.AudioChunk.SerializeToString,
                response_deserializer=voice__analysis__pb2.RiskAssessment.FromString,
                _registered_method=True)
        self.AnalyzeClip = channel.unary_unary(
                '/voiceintegrity.VoiceIntegrityService/AnalyzeClip',
                request_serializer=voice__analysis__pb2.AudioClip.SerializeToString,
                response_deserializer=voice__analysis__pb2.RiskAssessment.FromString,
                _registered_method=True)


class VoiceIntegrityServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def AnalyzeStream(self, request_iterator, context):
        """Client streams audio chunks; server streams back a risk assessment
        after every processed window.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeClip(self, request, context):
        """One-shot analysis of a short pre-recorded clip.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoiceIntegrityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeStream': grpc.stream_stream_rpc_method_handler(
                    servicer.AnalyzeStream,
                    request_deserializer=voice__analysis__pb2.AudioChunk.FromString,
                    response_serializer=voice__analysis__pb2.RiskAssessment.SerializeToString,
            ),
            'AnalyzeClip': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeClip,
                    request_deserializer=voice__analysis__pb2.AudioClip.FromString,
                    response_serializer=voice__analysis__pb2.RiskAssessment.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'voiceintegrity.VoiceIntegrityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('voiceintegrity.VoiceIntegrityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VoiceIntegrityService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/voiceintegrity.VoiceIntegrityService/AnalyzeStream',
            voice__analysis__pb2.AudioChunk.SerializeToString,
            voice__analysis__pb2.RiskAssessment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeClip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voiceintegrity.VoiceIntegrityService/AnalyzeClip',
            voice__analysis__pb2.AudioClip.SerializeToString,
            voice__analysis__pb2.RiskAssessment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
