# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: voice_analysis.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'voice_analysis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14voice_analysis.proto\x12\x0evoiceintegrity\"G\n\nAudioChunk\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x10\n\x08pcm_data\x18\x03 \x01(\x0c\"F\n\tAudioClip\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x10\n\x08pcm_data\x18\x03 \x01(\x0c\"\xca\x01\n\x0eRiskAssessment\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x12\n\nrisk_score\x18\x02 \x01(\x02\x12\x16\n\x0espectral_score\x18\x03 \x01(\x02\x12\x15\n\rprosody_score\x18\x04 \x01(\x02\x12\x19\n\x11\x63onsistency_score\x18\x05 \x01(\x02\x12\x11\n\trationale\x18\x06 \x01(\t\x12\x17\n\x0f\x61lert_triggered\x18\x07 \x01(\x08\x12\x1a\n\x12recommended_action\x18\x08 \x01(\t2\xb2\x01\n\x15VoiceIntegrityService\x12O\n\rAnalyzeStream\x12\x1a.voiceintegrity.AudioChunk\x1a\x1e.voiceintegrity.RiskAssessment(\x01\x30\x01\x12H\n\x0b\x41nalyzeClip\x12\x19.voiceintegrity.AudioClip\x1a\x1e.voiceintegrity.RiskAssessmentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voice_analysis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOCHUNK']._serialized_start=40
  _globals['_AUDIOCHUNK']._serialized_end=111
  _globals['_AUDIOCLIP']._serialized_start=113
  _globals['_AUDIOCLIP']._serialized_end=183
  _globals['_RISKASSESSMENT']._serialized_start=186
  _globals['_RISKASSESSMENT']._serialized_end=388
  _globals['_VOICEINTEGRITYSERVICE']._serialized_start=391
  _globals['_VOICEINTEGRITYSERVICE']._serialized_end=569
# @@protoc_insertion_point(module_scope)
